var canvas = document.getElementById('cv');
	var viewer = new JSC3D.Viewer(canvas);
	viewer.setParameter('SceneUrl', 'Falcon/starwars-millennium-falcon.obj');
	viewer.setParameter('InitRotationX', 0);
	viewer.setParameter('InitRotationY', 0);
	viewer.setParameter('InitRotationZ', 0);
	viewer.setParameter('ModelColor', '#CAA618');
	viewer.setParameter('BackgroundColor1', '#0000000');
	viewer.setParameter('BackgroundColor2', '#ffffff');
	viewer.setParameter('RenderMode', 'environment');
	viewer.setParameter('MipMapping', 'on');
	viewer.setParameter('Renderer', 'webgl');
	viewer.init();
	viewer.update();